# Generated by Django 5.1.1 on 2025-05-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("contenuP1", models.TextField(blank=True, null=True)),
                ("contenuConclusion", models.TextField(blank=True, null=True)),
                ("contenuSitation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("main_content", models.TextField()),
                ("quote", models.TextField(blank=True)),
                ("conclusion", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("article_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=328)),
                ("description", models.TextField()),
                ("photo500_x_800", models.ImageField(upload_to="PhotoFox")),
                ("photo800_x_533", models.ImageField(blank=True, upload_to="PhotoFox")),
                ("categorie", models.CharField(max_length=328)),
                ("auteur", models.CharField(blank=True, max_length=328)),
                ("date", models.DateField(auto_now_add=True)),
                ("contenuP1", models.TextField(blank=True, null=True)),
                ("contenuP2", models.TextField(blank=True, null=True)),
                ("contenuP3", models.TextField(blank=True, null=True)),
                ("contenuP4", models.TextField(blank=True, null=True)),
                ("contenuConclusion", models.TextField(blank=True, null=True)),
                ("contenuSitation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=328)),
                ("sousTitre", models.TextField()),
                ("photo", models.ImageField(upload_to="PhotoFox")),
                ("descriptionP1", models.TextField()),
                ("descriptionP2", models.TextField()),
                ("signature", models.ImageField(upload_to="PhotoFox")),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=328)),
                ("cv", models.FileField(blank=True, null=True, upload_to="FilesFox")),
                ("facebook", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedIn", models.URLField(blank=True)),
                ("gmail", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=328)),
                ("description", models.TextField()),
                (
                    "photo1_800_x_550",
                    models.ImageField(blank=True, upload_to="PhotoFox"),
                ),
                (
                    "photo2_800_x_550",
                    models.ImageField(blank=True, upload_to="PhotoFox"),
                ),
                (
                    "photo3_800_x_550",
                    models.ImageField(blank=True, upload_to="PhotoFox"),
                ),
                ("categorie", models.CharField(max_length=328)),
                ("sujet", models.CharField(blank=True, max_length=328)),
                ("date", models.DateField(blank=True)),
                ("demo", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Temoignage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("auteur", models.CharField(max_length=100)),
                ("fonction", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("periode", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ordre", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Visiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("objet", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "visiteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.visiteur"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.post"
                    ),
                ),
                (
                    "visiteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.visiteur"
                    ),
                ),
            ],
        ),
    ]
