# Generated by Django 5.2.1 on 2025-05-19 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "manual_add_date_inscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commentaire",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
