# Generated by Django 5.1.1 on 2025-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250518_0933"),
    ]

    operations = []
