# Generated by Django 5.1.1 on 2025-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_fix_models"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="annonce",
            table="FoxApp_annonce",
        ),
        migrations.AlterModelTable(
            name="commentaire",
            table="FoxApp_commentaire",
        ),
        migrations.AlterModelTable(
            name="message",
            table="FoxApp_message",
        ),
        migrations.AlterModelTable(
            name="newsletter",
            table="FoxApp_newsletter",
        ),
        migrations.AlterModelTable(
            name="post",
            table="FoxApp_post",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="FoxApp_profile",
        ),
        migrations.AlterModelTable(
            name="project",
            table="FoxApp_project",
        ),
        migrations.AlterModelTable(
            name="visiteur",
            table="FoxApp_visiteur",
        ),
    ]
